# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import edr_telemetry_pb2 as proto_dot_edr__telemetry__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/edr_telemetry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EDRTelemetryServiceStub:
    """==========================================
    EDR Telemetry & Command Stream Service
    ==========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/edr.telemetry.EDRTelemetryService/RegisterAgent',
                request_serializer=proto_dot_edr__telemetry__pb2.AgentInfo.SerializeToString,
                response_deserializer=proto_dot_edr__telemetry__pb2.RegistrationResponse.FromString,
                _registered_method=True)
        self.StreamTelemetry = channel.stream_stream(
                '/edr.telemetry.EDRTelemetryService/StreamTelemetry',
                request_serializer=proto_dot_edr__telemetry__pb2.TelemetryBatch.SerializeToString,
                response_deserializer=proto_dot_edr__telemetry__pb2.MitigationDirective.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/edr.telemetry.EDRTelemetryService/SendHeartbeat',
                request_serializer=proto_dot_edr__telemetry__pb2.Heartbeat.SerializeToString,
                response_deserializer=proto_dot_edr__telemetry__pb2.HeartbeatAck.FromString,
                _registered_method=True)


class EDRTelemetryServiceServicer:
    """==========================================
    EDR Telemetry & Command Stream Service
    ==========================================
    """

    def RegisterAgent(self, request, context):
        """Registers a remote endpoint agent with the SOC server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTelemetry(self, request_iterator, context):
        """High-throughput bidirectional telemetry and containment stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Periodic heartbeat keep-alive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EDRTelemetryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=proto_dot_edr__telemetry__pb2.AgentInfo.FromString,
                    response_serializer=proto_dot_edr__telemetry__pb2.RegistrationResponse.SerializeToString,
            ),
            'StreamTelemetry': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=proto_dot_edr__telemetry__pb2.TelemetryBatch.FromString,
                    response_serializer=proto_dot_edr__telemetry__pb2.MitigationDirective.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=proto_dot_edr__telemetry__pb2.Heartbeat.FromString,
                    response_serializer=proto_dot_edr__telemetry__pb2.HeartbeatAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edr.telemetry.EDRTelemetryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edr.telemetry.EDRTelemetryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EDRTelemetryService:
    """==========================================
    EDR Telemetry & Command Stream Service
    ==========================================
    """

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edr.telemetry.EDRTelemetryService/RegisterAgent',
            proto_dot_edr__telemetry__pb2.AgentInfo.SerializeToString,
            proto_dot_edr__telemetry__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/edr.telemetry.EDRTelemetryService/StreamTelemetry',
            proto_dot_edr__telemetry__pb2.TelemetryBatch.SerializeToString,
            proto_dot_edr__telemetry__pb2.MitigationDirective.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edr.telemetry.EDRTelemetryService/SendHeartbeat',
            proto_dot_edr__telemetry__pb2.Heartbeat.SerializeToString,
            proto_dot_edr__telemetry__pb2.HeartbeatAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
