/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiAlertsRouteImport } from './routes/api/alerts'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiReportsRouteImport } from './routes/api/reports'
import { Route as ApiRunRouteImport } from './routes/api/run'
import { Route as ApiScanRouteImport } from './routes/api/scan'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiReportsIdRouteImport } from './routes/api/reports.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsRoute = ApiAlertsRouteImport.update({
  id: '/api/alerts',
  path: '/api/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsRoute = ApiReportsRouteImport.update({
  id: '/api/reports',
  path: '/api/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunRoute = ApiRunRouteImport.update({
  id: '/api/run',
  path: '/api/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanRoute = ApiScanRouteImport.update({
  id: '/api/scan',
  path: '/api/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsIdRoute = ApiReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/reports': typeof ApiReportsRouteWithChildren
  '/api/run': typeof ApiRunRoute
  '/api/scan': typeof ApiScanRoute
  '/api/status': typeof ApiStatusRoute
  '/api/reports/$id': typeof ApiReportsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/reports': typeof ApiReportsRouteWithChildren
  '/api/run': typeof ApiRunRoute
  '/api/scan': typeof ApiScanRoute
  '/api/status': typeof ApiStatusRoute
  '/api/reports/$id': typeof ApiReportsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/reports': typeof ApiReportsRouteWithChildren
  '/api/run': typeof ApiRunRoute
  '/api/scan': typeof ApiScanRoute
  '/api/status': typeof ApiStatusRoute
  '/api/reports/$id': typeof ApiReportsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/alerts'
    | '/api/analyze'
    | '/api/reports'
    | '/api/run'
    | '/api/scan'
    | '/api/status'
    | '/api/reports/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/alerts'
    | '/api/analyze'
    | '/api/reports'
    | '/api/run'
    | '/api/scan'
    | '/api/status'
    | '/api/reports/$id'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/alerts'
    | '/api/analyze'
    | '/api/reports'
    | '/api/run'
    | '/api/scan'
    | '/api/status'
    | '/api/reports/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAlertsRoute: typeof ApiAlertsRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiReportsRoute: typeof ApiReportsRouteWithChildren
  ApiRunRoute: typeof ApiRunRoute
  ApiScanRoute: typeof ApiScanRoute
  ApiStatusRoute: typeof ApiStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts': {
      id: '/api/alerts'
      path: '/api/alerts'
      fullPath: '/api/alerts'
      preLoaderRoute: typeof ApiAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports': {
      id: '/api/reports'
      path: '/api/reports'
      fullPath: '/api/reports'
      preLoaderRoute: typeof ApiReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run': {
      id: '/api/run'
      path: '/api/run'
      fullPath: '/api/run'
      preLoaderRoute: typeof ApiRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan': {
      id: '/api/scan'
      path: '/api/scan'
      fullPath: '/api/scan'
      preLoaderRoute: typeof ApiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/$id': {
      id: '/api/reports/$id'
      path: '/$id'
      fullPath: '/api/reports/$id'
      preLoaderRoute: typeof ApiReportsIdRouteImport
      parentRoute: typeof ApiReportsRoute
    }
  }
}

interface ApiReportsRouteChildren {
  ApiReportsIdRoute: typeof ApiReportsIdRoute
}

const ApiReportsRouteChildren: ApiReportsRouteChildren = {
  ApiReportsIdRoute: ApiReportsIdRoute,
}

const ApiReportsRouteWithChildren = ApiReportsRoute._addFileChildren(
  ApiReportsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAlertsRoute: ApiAlertsRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiReportsRoute: ApiReportsRouteWithChildren,
  ApiRunRoute: ApiRunRoute,
  ApiScanRoute: ApiScanRoute,
  ApiStatusRoute: ApiStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
